{{- if .Values.secretproviderclass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretproviderclass.SecretProviderName }}
spec:
  provider: {{ .Values.secretproviderclass.SecretProvider }}
  secretObjects:
    - secretName: {{ .Values.secretproviderclass.secretName }}
      type: Opaque
      data:
      {{- range .Values.secretproviderclass.secrets }}
        {{- range .keys }}
        - objectName: {{ .value }}
          key: {{ .value }}
        {{- end }}
      {{- end }}
  parameters:
    objects: |
      {{- range .Values.secretproviderclass.secrets }}
      - objectName: {{ .objectName }}
        objectType: "secretsmanager"
        jmespath:
        {{- range .keys }}
          - path: {{ .path }}
            objectAlias: {{ .value }}
        {{- end }}
      {{- end }}
{{- end }}